### ISSUE TITLE
Today is Earth Day

### ISSUE THREAD

**Issue by theodoreng15** [nijal2000/The-Rainbow#9]
Today is Earth Day. It's an essential day that represents the world that we are living in. I am writing to u to demonstrate the importance of this poem. The rainbow poem is the only thing that can save this earth.

Here is a link to show earth without the poem

![image](https://user-images.githubusercontent.com/89175035/185970904-f392edd8-f5d4-4d85-a525-414e2e5e851e.png)

this is of upmost importance. only u. and u alone. can save the world. u have until tmmrw. good luck

Love,
theo

**Comment by nijal2000** [comment]
Cope+Seethe+Mald
